name: CI

# Executes on PR merges
# Another change in the comment
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches:
      [ master ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - name: Do a thing
        run: |
          TAG="$(API_TOKEN=248010fb2f4d055ecbcbdf2cf31f9bbaa97ed399 ./get_last_tag.rb)"
          echo $TAG

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: "248010fb2f4d055ecbcbdf2cf31f9bbaa97ed399"
          since_tag: "$TAG"

      - name: Commit files
        run: |
          cat CHANGELOG.md
          #git config --local user.email ${{ secrets.USER_EMAIL }}
          #git config --local user.name ${{ secrets.API_USER }}
          #git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
 
          #      - name: Push changes
          #        if: env.push == 1
          #        env:
          #          USER: ${{ secrets.API_USER }}
          #          TOKEN: ${{ secrets.API_KEY }}
          #        run: |
          #          git push "https://$USER:$TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
