# This will be executed on PR merges

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches: [ master ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: FUck you
        run: |
          echo "e04c39d5e5aba8ae2e595e1248918f9c6c40988c"
          echo $GITHUB_TOKEN

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1

      - name: Commit files
        run: |
          echo CHANGELOG.md
          git config --local user.email "ross@gmail.com"
          git config --local user.name "ross"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 1
        run: |
          git push "https://skyluk:e04c39d5e5aba8ae2e595e1248918f9c6c40988c@github.com/$GITHUB_REPOSITORY.git" HEAD:master

# jobs:
#   update-changelog:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     
#     - name: Update changelog
#       uses: thomaseizinger/keep-a-changelog-new-release@v1
#       with:
#         version: 'v1.0.1'
#
#     - name: Commit changes
#       run: |
#         git config --global user.email "skyluk@gmail.com"
#         git config --global user.name "Ross Fischer"
#         git add CHANGELOG.md
#         git commit CHAGNELOG.md -m "Updating CHANGELOG.md"
#         git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
