# This will be executed on PR merges

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          release_branch: 'master'
          since_tag: 'v1.2'

      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name ${{ secrets.API_USER }}
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 1
        env:
          USER: ${{ secrets.API_USER }}
          TOKEN: ${{ secrets.API_KEY }}
        run: |
          git push "https://$USER:$TOKENB@github.com/$GITHUB_REPOSITORY.git" HEAD:master
