# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: *

    - name: Commit changes
      run: |
        git config --global user.email "skyluk@gmail.com"
        git config --global user.name "Ross Fischer"
        git add CHANGELOG.md
        git commit CHAGNELOG.md -m "Updating CHANGELOG.md"
        git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
